### ISSUE TITLE
[BUG][Critical] Can't create a proposal

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#138]
The app doesn't trigger transaction in the wallet, therefore I am not able to create a proposal. This blocks further testing of the voting flow.

![Image](https://github.com/mento-protocol/governance-ui/assets/63065792/a3ae6b4c-e6d4-4915-8077-06739572b882)

**Comment by RyRy79261** [comment]
@olenovyk Which wallet are you using? 

And were there any errors in the console?

Did the wallet interact or receive requests correctly before this stage?

How long before this error did you connect your wallet and have your refreshed since then?

**Comment by bayological** [comment]
> @olenovyk Which wallet are you using? 
> 
> And were there any errors in the console?
> 
> Did the wallet interact or receive requests correctly before this stage?
> 
> How long before this error did you connect your wallet and have your refreshed since then?

Does this work on the test deployment?

**Comment by RyRy79261** [comment]
@bayological I was deploying proposals when I was deving so need to figure out what the client differences are

**Comment by RyRy79261** [comment]
I just successfully created a proposal on the test environment using the fix from #141
