### ISSUE TITLE
Add Cookie Policy Page

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/governance-ui#175]
### Requirements
- [ ] Get the cookie policy from Sandra (get in touch with her)
- [ ] Add an individual cookie policy page that has its own url
- [ ] On the cookie policy page, there should be a download link that downloads the cookie policy as a pdf

**Comment by philbow61** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/175?planning-poker) with Zenhub @nvtaveras @bayological
