### ISSUE TITLE
Fix veMENTO voting power displayed in "My locks" component

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#198]
**Description**
The veMENTO power is not being updated in the locker component on "[My voting power](https://governance.mento.org/my-voting-power)" page. It always shows the amount that was originally locked, but if i query balance of my locker from the smart contract, I get lower (actual) number.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09uQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4b4df9d834366d73793363fc761c71775ab330d3/Screenshot%202024-07-02%20at%2010.45.03.png" alt="Screenshot 2024-07-02 at 10.45.03.png" />

**Acceptance criteria**

- [ ] veMENTO balance in "My locks" component is updated dynamically based on user's current holdings

**Comment by chapati23** [comment]
@olenovyk needs design update after discussion in planning

multiple locks in the UI might be too confusing to the user
