### ISSUE TITLE
Finish SCSS clean up 

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#201]
## Description
We previously converted the app to use Tailwind instead of SCSS; however, some SCSS files remain. This issue is to complete the removal of all of the SCSS files and convert any remaining dependencies (if any) to Tailwind. 

## Acceptance Criteria
- [ ] All SCSS files are removed & app still looks and works as it should.

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/201?planning-poker) with Zenhub @chapati23 @denviljclarke @nvtaveras @philbow61
