### ISSUE TITLE
Allow users to view the Mento Governance parameters

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#21]
**Description**

After accessing the application, the user should be able to see the Mento Governance parameters in a collapsible section at the top of the page. In addition to this, they should be able to navigate to the following pages using buttons in the same visual component: 
- My Voting Power
- Create a new proposal

The section has two states: collapsed and expanded. 

**In the collapsed state, the following should be displayed:**

- Deployment chain (Celo)
- Token type (ERC-20)
- Total supply (1,000,000,000)
- Create new proposal button (always displayed for everyone)
- My voting power button should appear when the wallet is connected.

**In the expanded state, the following should be displayed**
(expands when user clicks on "Governance Parameters")
Governor parameters:
- Proposal threshold
- Quorum needed
- Voting period
- Timelock

The values displayed can be retrieved from the Govenor contract which can be retrieved using the SDK.

Contract addresses (contract addresses should be a clickable links going to the relevant page on celoscan, there should be a copy icon next to the address that allows user to copy the address):
- Governor
- Mento token
- Locker
- Timelock

The contract addresses should be retrieved from the Mento SDK.

NOTE: The values displayed should use the chain the user is connected to to retrieve the values. When no chain is connected the application should default to retrieving mainnet values. When the user is connected with an unsupported chain no information should be displayed with an error overlay to notify.

**Acceptance Criteria**
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **User should be able to view Mento Governance parameters**
  - The user should be able to see the Mento Governance parameters in a collapsible section at the top of the page.
  - The section should have two states: collapsed and expanded.
  - In the collapsed state, the following should be displayed:
    - Deployment chain (Celo)
    - Token type (ERC-20)
    - Total supply (1,000,000,000)
    - Create new proposal button (always displayed for everyone)
    - My voting power button should appear when the wallet is connected.
  - In the expanded state, the following should be displayed:
    - Governor parameters:
      - Proposal threshold
      - Quorum needed
      - Voting period
      - Timelock
  - The values displayed should be retrieved from the Governor contract using the SDK.
  - The contract addresses should be clickable links going to the relevant page on celoscan, and there should be a copy icon next to the address that allows the user to copy the address.
  - The contract addresses should be retrieved from the Mento SDK.
  - When the user is connected with an unsupported chain, no information should be displayed with an error overlay to notify.
  - When no chain is connected, the application should default to retrieving mainnet values.

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/tJicNwgOk0/estimate/4) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by olenovyk** [comment]
`NOTE: The values displayed should use the chain the user is connected to to retrieve the values. When no chain is connected the application should default to retrieving mainnet values. When the user is connected with an unsupported chain no information should be displayed with an error overlay to notify.`
Instead of an overlay let's display data for Celo Mainnet when user is connected to unsupported chain.
@denviljclarke
