### ISSUE TITLE
Lock Management - Provide tooltip feedback to inform multiple locks not supported

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#217]
**Description**
Our UI currently doesn't support multiple locks, but users can create them by calling the contract. This prevents us from supporting both scenarios with our current implementation. If we detect that a user has multiple locks, we should -

   - Set lock expiration to "Not available ℹ️" 
   - Disable the "Manage lock" button
   - On hover of both the expiration info and "Manage lock" button, show a which should read tooltip: "Multiple locks can't be managed right now in the UI."
   
   [Click here for tooltip code](https://ui.shadcn.com/docs/components/tooltip)
   [Click here for tooltip icon](https://lucide.dev/icons/circle-alert)
   

**Acceptance Criteria**

When multiple locks are detected for a user:
- [ ] The lock expiration field displays "Not available ℹ️" instead of the expiration date.
- [ ] The "Manage lock" button is visually disabled and non-interactive.
- [ ] The tooltip appears on hover of both the lock expiration info and the disabled "Manage lock" button.
- [ ] The tooltip displays the text: "Multiple locks can't be managed right now in the UI."

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/217?planning-poker) with Zenhub @bowd @chapati23 @denviljclarke @nvtaveras @RyRy79261
