### ISSUE TITLE
Lock Management - Allow users to update the parameters of an existing lock

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#218]
**Description**
Users with existing locks can only extend the duration of a current lock with the existing locked amount. We need to update the current implementation to allow users to add more tokens. 

User has a single lock:
   - The extent locks button should now read - "Mange Lock."
   - Update the dropdown to include a switch with the label - "update lock amount."
   - When the "update lock amount" switch is toggled, it should display an input similar to the [`Locking Input` component ](https://github.com/mento-protocol/governance-ui/blob/main/src/components/_shared/mento-lock/components/locking-input.tsx), which shows their MENTO balance & functionality to select max amount or type an amount.
   - If the lock amount input is populated, the amount locked should be updated with the selected date when the transaction is submitted

** Notes **
-  new input should be "Additional MENTO to lock" 
- input in the style of swap input i.e shows current (unlocked) mento balance, has "Use Max" functionality. 

   
   A round mock-up of how this should look can be found here
   [Click here to view mock-up](https://b_xmYP0N3.v0.build/)
  

**Acceptance Criteria**

 When users can update their lock with the:
- [ ]  Current expiration data and new amount
- [ ]  Current amount and new expiration date
- [ ]  New expiration date & new amount

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/218?planning-poker) with Zenhub @bowd @chapati23 @denviljclarke @nvtaveras @RyRy79261
