### ISSUE TITLE
Mobile - Proposal Page

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#228]
## Description

The current implementation of the proposal page doesn't match the designs for mobile. This issue is to implement the designs shown on Figma. 

Design - 
![Screenshot 2024-09-06 at 13 36 50](https://github.com/user-attachments/assets/c7f3781e-196a-4b98-a162-ebd73c7e05a1)

Current -
![Screenshot 2024-09-12 at 15 31 28](https://github.com/user-attachments/assets/00a4bbf9-8016-4b95-80d2-64a2b1b82e51)

[Click here to view them](https://www.figma.com/design/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?node-id=9177-14915&m=dev)

- [ ] Designs are implemented

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/228?planning-poker) with Zenhub @baroooo @bowd @chapati23 @denviljclarke @nvtaveras @philbow61 @RyRy79261
