### ISSUE TITLE
Allow users to vote on a proposal

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#23]
**Description**

On the proposal details page, if a user has connected their wallet and holds veMento, they should be able to vote on a proposal. When the wallet is connected, the cast vote component should display the amount of veMENTO (voting power) the user can allocate for this proposal. The user can click one of three buttons ('For', 'Against', 'Abstain') to send the transaction with the selected vote option using the SDK.

If the wallet is not connected, the user should be prompted to connect their wallet in order to vote.

If the user has already cast their votes, they should not be able to vote again. Instead, the text in the component should reflect the design [here](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=6847-3073&mode=dev).

[Component design in Figma](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=6847%3A3075&mode=design&t=oeezJpExpJOH1FAN-1)

**Acceptance Criteria**
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [x] **Scenario 1: User with connected wallet and veMento can vote on a proposal**
  - Given a user with a connected wallet and veMento
  - When the user navigates to the proposal details page
  - Then the user should see the cast vote component
  - And the component should display the amount of veMento the user can allocate for this
  - And user should be able click one of the three buttons ('For, 'Against',Abstain')
  - And the selected vote option should be sent as a transition

- [x] **Scenario 2: User without a wallet cannot vote on a proposal**
  - Given a user without a connected wallet
  - When the user navigates to the proposal details page
  - Then the user should see a prompt to connect their wallet in order to vote

- [x] **Scenario 3: User who has cast their votes cannot vote again**
  - Given a user who has already cast their votes
  - When the user navigates to the proposal details page
  - Then the user should see the cast vote component
  - And the component should display the text reflecting the design specified in the provided link

**Comment by bayological** [comment]
@olenovyk What does this mean "They can't change it"? They can't change their vote once cast?

**Comment by bayological** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/tYhknXDPJS/estimate/1) in Sprint Poker - 25th Jan

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by denviljclarke** [comment]
@olenovyk What should be displayed if the user is connected but they have 0 veMENTO, or any amount lower than the amount required to vote?

**Comment by olenovyk** [comment]
Hey @denviljclarke it should say that you have 0 veMENTO and need to lock some MENTO to vote. And have a link to locker component. I asked Nore to prep design for this case in this comment: https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa?node-id=6847:3075&mode=design#714751378

**Comment by denviljclarke** [comment]
> Hey @denviljclarke it should say that you have 0 veMENTO and need to lock some MENTO to vote. And have a link to locker component. I asked Nore to prep design for this case in this comment: https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa?node-id=6847:3075&mode=design#714751378

Perfect, thank you! I'll style this message based on current messages pending those designs
