### ISSUE TITLE
Lock Management - Information for users without tokens

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#230]
**Description**
We need to create an informative screen for users who don't have tokens. This screen will appear when a user without tokens accesses the `/voting-power` page, guiding them to the appropriate channels for obtaining tokens or learning more about our token governance system.

For a visual reference of how this screen should look, please refer to the following mock-up:
[Link to deployed mock-up example](https://b_ilWajgc.v0.build/)

**Acceptance Criteria**
- [ ] Display a clear, concise message explaining why the user can't access certain features
- [ ] Provide links to our twitter/x for obtaining tokens 
- [ ] Include a brief explanation of the benefits of token ownership
- [ ] Ensure the screen is responsive and works on both desktop and mobile devices

**Comment by bayological** [comment]
TBD
