### ISSUE TITLE
[BUG] Voting powers shown on the UI are incorrect

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/governance-ui#239]
#### Description

<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0dEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e0e6fc32dcc75dcf20390d43fe44e5af23e53fe/image.png" alt="image.png" />

The voting power calculations are wrong on the governance UI.

For votes on the UI calculated as 12m, correct number should be around 4m
Percentages shown on the right pane are also wrong

#### Acceptance Criteria
- [ ] Gov UI shows correct voting power
- [ ] Gov UI shows correct percentages

**Comment by RyRy79261** [comment]
The Subgraph is reporting the same weights, not a UI issue at present, will investigate
