### ISSUE TITLE
Display list of voters in participants section

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#24]
**Description**
When a user is on the page for a specific proposal, the participant's section should display the complete list of all addresses that have voted on the proposal. The addresses should be separated by the vote type (For, Against, Abstain) and should also show the following:
- Total number of addresses that have voted
- The % of total votes for each voter

**Acceptance Criteria**
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Display list of voters in participants section**
  - Given a user is on the page for a specific proposal
  - When the participant's section is displayed
  - Then the complete list of all addresses that have voted on the proposal should be shown
  - And the addresses should be separated by the vote type (For, Against, Abstain)
  - And the total number of addresses that have voted should be displayed
  - And the % of total votes for each voter should be shown

**Comment by bowd** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/u9UjxLPvr2/estimate/2) in Sprint Poker #​​34

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
