### ISSUE TITLE
ve-Locking component

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#26]
*Description*
The voting component should allow users with MENTO in their connected wallet to choose a lock period and lock their tokens as veMENTO.

It consists of 5 sub-components:

1. Amount of MENTO to lock.
   - An input field that allows users to specify how much MENTO they want to lock.
   - Should have a "Max." hint under the input that displays the current MENTO balance of the connected wallet
   - When clicking the "Max." hint, it should auto-populate the input with the max number of tokens
   - When users enter more MENTO tokens than they currently have in their wallet, it should show a warning message 
2. Lock duration. A dropdown calendar that allows users to pick their desired lock end date
   - Date must be in the future (past can not be selected)
   - Date can not be further than 2 years away from now (dates further than 2 years from now can't be selected)
   - Calendar should only allow to select Wednesdays since locks work only from Wednesday till Wednesday in the smart contract
3. veMENTO received. Displays the amount of veMENTO voting power users will receive based on their entered MENTO amount and lock period.
4. Slider. Duplicates the function of the dropdown calendar component. When a user interacts with one of them, the change should be reflected in the other one.
5. Lock MENTO. A button that triggers a `lock` transaction on the smart contract using the provided amount and lock period parameters

[Component design in Figma](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airgrab?type=design&node-id=6395%3A8397&mode=design&t=31llJCsqoFj3PCbL-1)

**Comment by bayological** [comment]
@bowd will spec this out based on the existing UI. We can create an issue in future to make any UI updates

**Comment by RyRy79261** [comment]
Potentially cherry picking UI to make a new branch to accommodate the refactor
