### ISSUE TITLE
Display all locks for connected user

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#27]
**Description**
When a connected user clicks the "My voting power" button on the home page, the app should display the my voting power page. The page should allow the user to see their current locks.

Each veMENTO holder can have multiple locks. The "My Locks" component should list all the user's locks as a table with the following columns:
- Amount of MENTO locked
- Amount of veMENTO recieved
- Date when this lock expires
- A button to extend the lock. When clicked, the user should see a calendar in the popup (same as the one that is used in locking component) where they can choose a date in the future after current lock's expiration data and confirm their choice). This should trigger onchain transaction.

 **Acceptance Criteria**
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Displaying My Locks**
  - Given a connected user on the home page
  - When the user clicks the "My voting power" button
  - Then the app should display the "My voting power" page
  - And the page should allow the user to see their current locks

- [ ] **Scenario 2: Listing User's Locks**
  - Given a connected user on the "My voting power" page
  - When the page loads
  - Then the "My Locks" component should be displayed
  - And the component should list all the user's locks as a table
  - And the table should have the following columns:
    - Amount of MENTO locked
    - Amount of veMENTO received
    - Date when this lock expires
    - A button to extend the lock

- [ ] **Scenario 3: Extending Lock**
  - Given a connected user on the "My Locks" component
  - When the user clicks the "Extend lock" button for a specific lock
  - Then a popup should appear
  - And the popup should display a calendar
  - And the calendar should only allow the user to choose a date in the future after the current lock's expiration date
  - And the user should be able to confirm their choice
  - And confirming the choice should trigger an onchain transaction

**Comment by bowd** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/u9UjxLPvr2/estimate/1) in Sprint Poker #​​34

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
