### ISSUE TITLE
Add T&Cs popup

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/governance-ui#88]
## Description
To make sure that users review and accept Airdrop Terms we should add a popup that appears on the first visit to airdrop app.
The user is supposed to scroll down to the bottom of T&Cs text, click the checkbox "I have read, understand and accept these terms" before CTA "Agree and continue" will become active.
It should not be possible to proceed without accepting T&Cs.
For returning users the popup should not appear (save in local storage the fact that user has already accepted it).
[Design in Figma, desktop](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=8863%3A6949&mode=design&t=QGdyxtQ5tu0El6dx-1)
[Design in Figma, mobile](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=8863%3A6796&mode=design&t=QGdyxtQ5tu0El6dx-1)
[File with T&Cs](https://docs.google.com/document/d/1f3v9EPaIWsqLuoTl584YX1j6_EklH-W0/edit?usp=sharing&ouid=109498475265340717760&rtpof=true&sd=true)

## Acceptance criteria

- [x] T&C popup is implemented according to the design

**Comment by bowd** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/vtc4Vre0og/estimate/4) in Sprint Poker #​​39

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by AnnaJ-P11** [comment]
The popup is done, but the mobile version needs to be refined and there is no support for its display and it is not tested. My current code is uploaded to branch feat/add-T&Cs-popup in the airgbrab-interface repository
