### ISSUE TITLE
Implement `Write` actions in contracts

### ISSUE THREAD

**Issue by RyRy79261** [mento-protocol/governance-ui#91]
## Overview

Currently, some of the write actions are not available. 

This ticket is to create the necessary hooks for the available write actions. Simulation functions will also be needed.

## Acceptance criteria 

- Approve Mento transfer 
  - [ ] Simulation function
  - [ ] Execute function
- Lock for veMento 
  - [ ] Simulation function
  - [ ] Execute function
- Create proposal 
  - [ ] Simulation function
  - [ ] Execute function
- Vote 
  - [ ] Simulation function
  - [ ] Execute function

**Comment by bayological** [comment]
@RyRy79261 Vote is already implemented

**Comment by denviljclarke** [comment]
@RyRy79261, We can break this up. I'll implement the locking logic as I'm working on  [this issue](https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/governance-ui/26) which requires locking logic. You can then work on create proposal when you're ready.
