### ISSUE TITLE
Modal component: Implementing generic modal/dialog

### ISSUE THREAD

**Issue by RyRy79261** [mento-protocol/governance-ui#92]
## Over view 

A standard styled modal should be created. 

This should leverage tailwind components and have certain custmizations. 

An appropriate tailwind based modal package can be used, provided its light weight.

### Option 1: Prebuiilt

- [ ] Something like [TailwindUI`s dialog component](https://tailwindui.com/components/application-ui/overlays/dialogs)

### Option 2: Manually created 

-  Modal provider & hook
  - [ ] A generic modal/dialog component that handles the open & closing logic
  - [ ] The component should take an open state, a `set open` function `setOpen: (state: boolean) => void`
  - [ ] The modal/dialog wrapper basically just handles `Transition`, click off area & actual content area, anything else is up to the specific component itself

**Comment by RyRy79261** [comment]
@denviljclarke Do you have any preferred/suggested approaches for this?

**Comment by denviljclarke** [comment]
I think we should use [Tailwind / Headless UI's Modal](https://headlessui.com/react/dialog). It's pretty straight forward. You expand the scope of this ticket to replace the existing modals with this modal and assign me 🫡
