### ISSUE TITLE
Mobile Optimization - Proposal List

### ISSUE THREAD

**Issue by denviljclarke** [mento-protocol/governance-ui#98]
## Overview

Currently the proposal list on the home screen is not optimized for mobile, this issue is to make the necessary styling and layout changes to the proposal list so it matches [the designs ](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=8145-3203&mode=design&t=6UemNGemNlukoJnv-4)

## Acceptance criteria 

- [ ] Proposal list should [match the designs ](https://www.figma.com/file/QSQsvksBOspBTONiBBFpqa/MENTO-Airdrop-%26-Governance-UIs?type=design&node-id=8145-3203&mode=design&t=6UemNGemNlukoJnv-4)

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/governance-ui/98?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke
